# This is main config file for PcControl Server-Side App

settings:
   
   # What folders client will be able to see in the list and enter. Default: *
   folders-allowed-to-see:
      - all
   
   # What folders client will be able to execute files in and single file derictories.
   folders-and-files-allowed-to-use-execution:
      - "G:/"

config-version: 1.0.0-2